/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cookbook;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.nio.file.Files;
import java.nio.file.Paths;

class AppTest {
    @Test void appHasAGreeting() {
        // App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        /* try {
            //String json = new String(Files.readAllBytes());
            System.out.println(Paths.get("app/src/main/java/cookbook/dbTools/seeding.json"));
        } catch (Exception e) {
            System.out.println(e);
        } */
    }
}
